sudo: required # Docker needs sudo
services:
  - docker

before_install: # initial setup
  - docker build -t vampirekiddo/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true vampirekiddo/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "frontend"
  env: "Frontend-dev"
  bucket_name: "elasticbeanstalk-eu-central-1-992382526604"
  bucket_path: "docker"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
