sudo: required # Docker needs sudo
services:
  - docker

before_install: # initial setup
  - docker build -t vampirekiddo/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true vampirekiddo/docker-react npm run test
